export type SupportedLocale = "en" | "es" | "gl";

export type TranslationKey = keyof typeof TRANSLATIONS.en;

const TRANSLATIONS = {
  en: {
    required_config: "Configuration is required",
    vehicle: "Vehicle",
    connected_vehicle: "Connected vehicle",
    select_vehicle: "Select a vehicle in the editor.",
    locked: "Locked",
    unlocked: "Unlocked",
    unknown_state: "Unknown state",
    updated_now: "Updated now",
    updated_minutes: "Updated {count} min ago",
    updated_hours: "Updated {count} h ago",
    no_update_date: "No update date",
    stale_data: "Vehicle data may be outdated",
    range: "Range",
    battery: "Battery",
    odometer: "Odometer",
    trip_distance: "Distance this month",
    trip_consumption: "Average consumption",
    trip_duration: "Driving time",
    doors: "Doors",
    windows: "Windows",
    trunk: "Trunk",
    hood: "Hood",
    lights: "Lights",
    charging: "Charging",
    open: "Open",
    closed: "Closed",
    on: "On",
    off: "Off",
    active: "Active",
    inactive: "Inactive",
    unavailable: "No data",
    unlock: "Unlock",
    lock: "Lock",
    climate: "Climate",
    refresh: "Refresh",
    refresh_cached: "Refresh cached data",
    refresh_from_car: "Refresh from car",
    horn_lights: "Horn & lights",
    location: "Location",
    confirm_unlock: "Unlock the vehicle doors?",
    action_failed: "The vehicle action could not be completed.",
    discovery_failed: "Vehicle entities could not be discovered.",
    action_in_progress: "Action in progress",
    vehicle_controls: "Vehicle controls",
    diagnostics: "Diagnostics",
    copy_diagnostics: "Copy anonymized diagnostics",
    diagnostics_copied: "Diagnostics copied",
    custom_image_failed: "The custom image could not be loaded. Showing the Honda fallback.",
    editor_vehicle: "Vehicle",
    editor_select_vehicle: "Select a My Honda+ vehicle",
    editor_searching_vehicles: "Searching for vehicles…",
    editor_vehicles_found: "Vehicles found: {count}",
    editor_name: "Name",
    editor_visual_model: "Visual model",
    editor_automatic: "Automatic",
    editor_generic_honda: "Generic Honda",
    editor_appearance: "Appearance",
    editor_layout: "Layout",
    editor_full: "Full",
    editor_compact: "Compact",
    editor_vehicle_scale: "Vehicle scale (%)",
    editor_alignment: "Alignment",
    editor_left: "Left",
    editor_center: "Center",
    editor_right: "Right",
    editor_show_shadow: "Show color shadow",
    editor_shadow_color: "Shadow color",
    editor_custom: "Custom",
    editor_custom_shadow_color: "Custom shadow color",
    editor_shadow_intensity: "Shadow intensity (%)",
    editor_image: "Image",
    editor_included_art: "Included artwork",
    editor_custom_image: "Custom image",
    editor_image_url: "Image URL",
    editor_content: "Content",
    editor_metrics: "Metrics",
    editor_controls: "Controls",
    editor_locking: "Locking",
    editor_behavior: "Behavior",
    editor_language: "Language",
    editor_stale_after: "Data considered stale after (seconds)",
    editor_show_controls: "Show controls",
    editor_show_model: "Show model",
    editor_allow_animations: "Allow animations",
    editor_confirm_unlock: "Confirm before unlocking",
    editor_show_diagnostics: "Show anonymized diagnostics",
    editor_not_available: "not available",
  },
  es: {
    required_config: "La configuración es obligatoria",
    vehicle: "Vehículo",
    connected_vehicle: "Vehículo conectado",
    select_vehicle: "Selecciona el vehículo en el editor.",
    locked: "Cerrado",
    unlocked: "Desbloqueado",
    unknown_state: "Estado desconocido",
    updated_now: "Actualizado ahora",
    updated_minutes: "Actualizado hace {count} min",
    updated_hours: "Actualizado hace {count} h",
    no_update_date: "Sin fecha de actualización",
    stale_data: "Los datos del vehículo pueden estar desactualizados",
    range: "Autonomía",
    battery: "Batería",
    odometer: "Kilometraje",
    trip_distance: "Distancia este mes",
    trip_consumption: "Consumo medio",
    trip_duration: "Tiempo de conducción",
    doors: "Puertas",
    windows: "Ventanas",
    trunk: "Maletero",
    hood: "Capó",
    lights: "Luces",
    charging: "Carga",
    open: "Abierto",
    closed: "Cerrado",
    on: "Encendidas",
    off: "Apagadas",
    active: "Activa",
    inactive: "Inactiva",
    unavailable: "Sin datos",
    unlock: "Abrir",
    lock: "Cerrar",
    climate: "Clima",
    refresh: "Actualizar",
    refresh_cached: "Actualizar datos guardados",
    refresh_from_car: "Actualizar desde el coche",
    horn_lights: "Bocina y luces",
    location: "Ubicación",
    confirm_unlock: "¿Abrir las puertas del vehículo?",
    action_failed: "No se pudo completar la acción del vehículo.",
    discovery_failed: "No se pudieron detectar las entidades del vehículo.",
    action_in_progress: "Acción en curso",
    vehicle_controls: "Controles del vehículo",
    diagnostics: "Diagnóstico",
    copy_diagnostics: "Copiar diagnóstico anonimizado",
    diagnostics_copied: "Diagnóstico copiado",
    custom_image_failed: "No se pudo cargar la imagen personalizada. Se muestra el logo de Honda.",
    editor_vehicle: "Vehículo",
    editor_select_vehicle: "Selecciona un vehículo My Honda+",
    editor_searching_vehicles: "Buscando vehículos…",
    editor_vehicles_found: "Vehículos encontrados: {count}",
    editor_name: "Nombre",
    editor_visual_model: "Modelo visual",
    editor_automatic: "Automático",
    editor_generic_honda: "Honda genérico",
    editor_appearance: "Apariencia",
    editor_layout: "Diseño",
    editor_full: "Completo",
    editor_compact: "Compacto",
    editor_vehicle_scale: "Escala del vehículo (%)",
    editor_alignment: "Alineación",
    editor_left: "Izquierda",
    editor_center: "Centro",
    editor_right: "Derecha",
    editor_show_shadow: "Mostrar sombra de color",
    editor_shadow_color: "Color de la sombra",
    editor_custom: "Personalizado",
    editor_custom_shadow_color: "Color personalizado de la sombra",
    editor_shadow_intensity: "Intensidad de la sombra (%)",
    editor_image: "Imagen",
    editor_included_art: "Ilustración incluida",
    editor_custom_image: "Imagen personalizada",
    editor_image_url: "URL de imagen",
    editor_content: "Contenido",
    editor_metrics: "Métricas",
    editor_controls: "Controles",
    editor_locking: "Cierre",
    editor_behavior: "Comportamiento",
    editor_language: "Idioma",
    editor_stale_after: "Datos antiguos después de (segundos)",
    editor_show_controls: "Mostrar controles",
    editor_show_model: "Mostrar modelo",
    editor_allow_animations: "Permitir animaciones",
    editor_confirm_unlock: "Confirmar antes de abrir",
    editor_show_diagnostics: "Mostrar diagnóstico anonimizado",
    editor_not_available: "no disponible",
  },
  gl: {
    required_config: "A configuración é obrigatoria",
    vehicle: "Vehículo",
    connected_vehicle: "Vehículo conectado",
    select_vehicle: "Selecciona o vehículo no editor.",
    locked: "Pechado",
    unlocked: "Desbloqueado",
    unknown_state: "Estado descoñecido",
    updated_now: "Actualizado agora",
    updated_minutes: "Actualizado hai {count} min",
    updated_hours: "Actualizado hai {count} h",
    no_update_date: "Sen data de actualización",
    stale_data: "Os datos do vehículo poden estar desactualizados",
    range: "Autonomía",
    battery: "Batería",
    odometer: "Quilometraxe",
    trip_distance: "Distancia este mes",
    trip_consumption: "Consumo medio",
    trip_duration: "Tempo de condución",
    doors: "Portas",
    windows: "Xanelas",
    trunk: "Maleteiro",
    hood: "Capó",
    lights: "Luces",
    charging: "Carga",
    open: "Aberto",
    closed: "Pechado",
    on: "Acesas",
    off: "Apagadas",
    active: "Activa",
    inactive: "Inactiva",
    unavailable: "Sen datos",
    unlock: "Abrir",
    lock: "Pechar",
    climate: "Clima",
    refresh: "Actualizar",
    refresh_cached: "Actualizar datos gardados",
    refresh_from_car: "Actualizar desde o coche",
    horn_lights: "Bucina e luces",
    location: "Localización",
    confirm_unlock: "Abrir as portas do vehículo?",
    action_failed: "Non se puido completar a acción do vehículo.",
    discovery_failed: "Non se puideron detectar as entidades do vehículo.",
    action_in_progress: "Acción en curso",
    vehicle_controls: "Controis do vehículo",
    diagnostics: "Diagnóstico",
    copy_diagnostics: "Copiar diagnóstico anonimizado",
    diagnostics_copied: "Diagnóstico copiado",
    custom_image_failed: "Non se puido cargar a imaxe personalizada. Móstrase o logo de Honda.",
    editor_vehicle: "Vehículo",
    editor_select_vehicle: "Selecciona un vehículo My Honda+",
    editor_searching_vehicles: "Buscando vehículos…",
    editor_vehicles_found: "Vehículos atopados: {count}",
    editor_name: "Nome",
    editor_visual_model: "Modelo visual",
    editor_automatic: "Automático",
    editor_generic_honda: "Honda xenérico",
    editor_appearance: "Aparencia",
    editor_layout: "Deseño",
    editor_full: "Completo",
    editor_compact: "Compacto",
    editor_vehicle_scale: "Escala do vehículo (%)",
    editor_alignment: "Aliñamento",
    editor_left: "Esquerda",
    editor_center: "Centro",
    editor_right: "Dereita",
    editor_show_shadow: "Mostrar sombra de cor",
    editor_shadow_color: "Cor da sombra",
    editor_custom: "Personalizado",
    editor_custom_shadow_color: "Cor personalizada da sombra",
    editor_shadow_intensity: "Intensidade da sombra (%)",
    editor_image: "Imaxe",
    editor_included_art: "Ilustración incluída",
    editor_custom_image: "Imaxe personalizada",
    editor_image_url: "URL da imaxe",
    editor_content: "Contido",
    editor_metrics: "Métricas",
    editor_controls: "Controis",
    editor_locking: "Pechadura",
    editor_behavior: "Comportamento",
    editor_language: "Idioma",
    editor_stale_after: "Datos antigos despois de (segundos)",
    editor_show_controls: "Mostrar controis",
    editor_show_model: "Mostrar modelo",
    editor_allow_animations: "Permitir animacións",
    editor_confirm_unlock: "Confirmar antes de abrir",
    editor_show_diagnostics: "Mostrar diagnóstico anonimizado",
    editor_not_available: "non dispoñible",
  },
} as const;

export function normalizeLocale(locale?: string): SupportedLocale {
  const language = locale?.toLowerCase().split(/[-_]/)[0];
  return language === "en" || language === "gl" ? language : "es";
}

export function localize(
  key: TranslationKey,
  locale?: string,
  replacements: Record<string, string | number> = {},
): string {
  const language = normalizeLocale(locale);
  let text: string = TRANSLATIONS[language][key];
  for (const [name, value] of Object.entries(replacements)) {
    text = text.replaceAll(`{${name}}`, String(value));
  }
  return text;
}
