export type SupportedLocale = "en" | "es" | "gl";

export type TranslationKey = keyof typeof TRANSLATIONS.en;

const TRANSLATIONS = {
  en: {
    required_config: "Configuration is required",
    vehicle: "Vehicle",
    connected_vehicle: "Connected vehicle",
    select_vehicle: "Select a vehicle in the editor.",
    locked: "Locked",
    unlocked: "Unlocked",
    unknown_state: "Unknown state",
    updated_now: "Updated now",
    updated_minutes: "Updated {count} min ago",
    updated_hours: "Updated {count} h ago",
    no_update_date: "No update date",
    stale_data: "Vehicle data may be outdated",
    range: "Range",
    battery: "Battery",
    odometer: "Odometer",
    doors: "Doors",
    windows: "Windows",
    trunk: "Trunk",
    hood: "Hood",
    lights: "Lights",
    charging: "Charging",
    open: "Open",
    closed: "Closed",
    on: "On",
    off: "Off",
    active: "Active",
    inactive: "Inactive",
    unlock: "Unlock",
    lock: "Lock",
    climate: "Climate",
    refresh: "Refresh",
    location: "Location",
    confirm_unlock: "Unlock the vehicle doors?",
    action_failed: "The vehicle action could not be completed.",
    discovery_failed: "Vehicle entities could not be discovered.",
    action_in_progress: "Action in progress",
  },
  es: {
    required_config: "La configuración es obligatoria",
    vehicle: "Vehículo",
    connected_vehicle: "Vehículo conectado",
    select_vehicle: "Selecciona el vehículo en el editor.",
    locked: "Cerrado",
    unlocked: "Desbloqueado",
    unknown_state: "Estado desconocido",
    updated_now: "Actualizado ahora",
    updated_minutes: "Actualizado hace {count} min",
    updated_hours: "Actualizado hace {count} h",
    no_update_date: "Sin fecha de actualización",
    stale_data: "Los datos del vehículo pueden estar desactualizados",
    range: "Autonomía",
    battery: "Batería",
    odometer: "Kilometraje",
    doors: "Puertas",
    windows: "Ventanas",
    trunk: "Maletero",
    hood: "Capó",
    lights: "Luces",
    charging: "Carga",
    open: "Abierto",
    closed: "Cerrado",
    on: "Encendidas",
    off: "Apagadas",
    active: "Activa",
    inactive: "Inactiva",
    unlock: "Abrir",
    lock: "Cerrar",
    climate: "Clima",
    refresh: "Actualizar",
    location: "Ubicación",
    confirm_unlock: "¿Abrir las puertas del vehículo?",
    action_failed: "No se pudo completar la acción del vehículo.",
    discovery_failed: "No se pudieron detectar las entidades del vehículo.",
    action_in_progress: "Acción en curso",
  },
  gl: {
    required_config: "A configuración é obrigatoria",
    vehicle: "Vehículo",
    connected_vehicle: "Vehículo conectado",
    select_vehicle: "Selecciona o vehículo no editor.",
    locked: "Pechado",
    unlocked: "Desbloqueado",
    unknown_state: "Estado descoñecido",
    updated_now: "Actualizado agora",
    updated_minutes: "Actualizado hai {count} min",
    updated_hours: "Actualizado hai {count} h",
    no_update_date: "Sen data de actualización",
    stale_data: "Os datos do vehículo poden estar desactualizados",
    range: "Autonomía",
    battery: "Batería",
    odometer: "Quilometraxe",
    doors: "Portas",
    windows: "Xanelas",
    trunk: "Maleteiro",
    hood: "Capó",
    lights: "Luces",
    charging: "Carga",
    open: "Aberto",
    closed: "Pechado",
    on: "Acesas",
    off: "Apagadas",
    active: "Activa",
    inactive: "Inactiva",
    unlock: "Abrir",
    lock: "Pechar",
    climate: "Clima",
    refresh: "Actualizar",
    location: "Localización",
    confirm_unlock: "Abrir as portas do vehículo?",
    action_failed: "Non se puido completar a acción do vehículo.",
    discovery_failed: "Non se puideron detectar as entidades do vehículo.",
    action_in_progress: "Acción en curso",
  },
} as const;

export function normalizeLocale(locale?: string): SupportedLocale {
  const language = locale?.toLowerCase().split(/[-_]/)[0];
  return language === "en" || language === "gl" ? language : "es";
}

export function localize(
  key: TranslationKey,
  locale?: string,
  replacements: Record<string, string | number> = {},
): string {
  const language = normalizeLocale(locale);
  let text: string = TRANSLATIONS[language][key];
  for (const [name, value] of Object.entries(replacements)) {
    text = text.replaceAll(`{${name}}`, String(value));
  }
  return text;
}
